Instructions:

Adapt our reinforcement learning algorithm to solve the mountain car problem. Start with existing notebook.ipynb code, substitute new environment, change state discretization functions, and try to make existing algorithm to train with minimal code modifications. Optimize the result by adjusting hyperparameters.

In [19]:
import matplotlib.pyplot as plt
import numpy as np 
import sys
import gym
import random
import pygame

In [20]:
env = gym.make("CartPole-v1", render_mode='rgb_array')
print(env.action_space)
print(env.observation_space)
print(env.action_space.sample())

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
1


In [21]:
env.reset()

for i in range(100):
   env.render()
   env.step(env.action_space.sample())
env.close()

c:\Users\PC\anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


In [22]:
env = gym.make("CartPole-v1", render_mode = "rgb_array")
obs, info = env.reset()

for _ in range(100):
    action = env.action_space.sample()  
    obs, rew, tmt, trct, info = env.step(action)
    print(f"{obs} -> {rew}")

    if tmt or trct:
        ob, info = env.reset()

env.close()

[-0.04054593  0.19904083 -0.02722638 -0.2584475 ] -> 1.0
[-0.03656511  0.39454067 -0.03239533 -0.5595922 ] -> 1.0
[-0.02867429  0.19988805 -0.04358717 -0.27728897] -> 1.0
[-0.02467653  0.00541416 -0.04913295  0.00133424] -> 1.0
[-0.02456825  0.20120506 -0.04910627 -0.306437  ] -> 1.0
[-0.02054415  0.00681601 -0.05523501 -0.02963633] -> 1.0
[-0.02040783  0.20268477 -0.05582773 -0.33922225] -> 1.0
[-0.01635413  0.00839981 -0.06261218 -0.06465366] -> 1.0
[-0.01618614  0.20436096 -0.06390525 -0.37641537] -> 1.0
[-0.01209892  0.40032962 -0.07143356 -0.6885437 ] -> 1.0
[-0.00409233  0.20626797 -0.08520443 -0.41917717] -> 1.0
[ 3.303389e-05  4.024874e-01 -9.358798e-02 -7.374584e-01] -> 1.0
[ 0.00808278  0.5987687  -0.10833714 -1.0580666 ] -> 1.0
[ 0.02005816  0.4052358  -0.12949848 -0.8012581 ] -> 1.0
[ 0.02816287  0.21210513 -0.14552364 -0.551954  ] -> 1.0
[ 0.03240497  0.4089388  -0.15656272 -0.88671684] -> 1.0
[ 0.04058375  0.21624885 -0.17429705 -0.6470587 ] -> 1.0
[ 0.04490873  0.0239286

State Discretization:

In [23]:
def discretize(x):
    return tuple((x/np.array([0.25, 0.25, 0.01, 0.1])).astype(np.int))

In [24]:
def create_bins(i,num):
    return np.arange(num+1)*(i[1]-i[0])/num+i[0]

print("Sample bins for interval (-5,5) with 10 bins\n",create_bins((-5,5),10))

ints = [(-5,5),(-2,2),(-0.5,0.5),(-2,2)] 
nbins = [20,20,10,10] 
bins = [create_bins(ints[i],nbins[i]) for i in range(4)]

def discretize_bins(x):
    return tuple(np.digitize(x[i],bins[i]) for i in range(4))

Sample bins for interval (-5,5) with 10 bins
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
